// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClR9gV_285DgJviVaWvZrgkc2_Bb2wNwQ',
    appId: '1:422412778152:android:83c2b403a662f58e24e09d',
    messagingSenderId: '422412778152',
    projectId: 'ppdeli-f07a9',
    authDomain: 'ppdeli-f07a9.firebaseapp.com',
    databaseURL: 'https://ppdeli-f07a9-default-rtdb.firebaseio.com',
    storageBucket: 'ppdeli-f07a9.firebasestorage.app',
    measurementId: 'G-EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClR9gV_285DgJviVaWvZrgkc2_Bb2wNwQ',
    appId: '1:422412778152:android:83c2b403a662f58e24e09d',
    messagingSenderId: '422412778152',
    projectId: 'ppdeli-f07a9',
    databaseURL: 'https://ppdeli-f07a9-default-rtdb.firebaseio.com',
    storageBucket: 'ppdeli-f07a9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClR9gV_285DgJviVaWvZrgkc2_Bb2wNwQ',
    appId: '1:422412778152:android:83c2b403a662f58e24e09d',
    messagingSenderId: '422412778152',
    projectId: 'ppdeli-f07a9',
    databaseURL: 'https://ppdeli-f07a9-default-rtdb.firebaseio.com',
    storageBucket: 'ppdeli-f07a9.firebasestorage.app',
    androidClientId: '422412778152-rcdirb48435tifo5pslno4dplan1bhcm.apps.googleusercontent.com',
    iosClientId: '42778152-ablkcj4mun7pd5usjae0m2lcgv9a5v3n.apps.googleusercontent.com',
    iosBundleId: 'com.ppdeli.deliverystore',
  );
}
